In [613]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

In [614]:
data_m = pd.read_excel("Data set 10 years (1).xlsx")

In [615]:
data_m

    R1 R2 R3 R4 R5 R6 R7 R8 R9 R10 R11 R12 R13 R14          Unnamed: 14
0    L  E  E  Z  Z  L  Z  E  L   L   L   E   E   E           30/08/2021
1    Z  E  E  E  E  L  Z  E  E   Z   Z   Z   E   E           23/08/2021
2    E  L  Z  E  L  E  E  Z  L   Z   Z   E   Z   L           16/08/2021
3    E  Z  Z  E  E  E  L  Z  Z   L   Z   L   L   L  2021-08-08 00:00:00
4    Z  L  L  E  Z  L  Z  E  Z   E   Z   Z   E   L  2021-02-08 00:00:00
..  .. .. .. .. .. .. .. .. ..  ..  ..  ..  ..  ..                  ...
557  E  L  L  L  Z  Z  E  E  L   Z   L   E   Z   E           31/01/2010
558  L  E  L  Z  L  Z  E  E  L   Z   L   L   L   Z           24/01/2010
559  Z  L  L  E  Z  L  L  L  E   L   Z   L   L   L           17/01/2010
560  L  Z  L  Z  L  L  Z  L  E   L   Z   L   E   Z  2010-10-01 00:00:00
561  L  L  L  E  L  L  L  E  L   E   Z   E   E   Z  2010-03-01 00:00:00

[562 rows x 15 columns]

In [616]:
data_new = data_m.drop("Unnamed: 14", axis = 'columns')

In [617]:
data_new

    R1 R2 R3 R4 R5 R6 R7 R8 R9 R10 R11 R12 R13 R14
0    L  E  E  Z  Z  L  Z  E  L   L   L   E   E   E
1    Z  E  E  E  E  L  Z  E  E   Z   Z   Z   E   E
2    E  L  Z  E  L  E  E  Z  L   Z   Z   E   Z   L
3    E  Z  Z  E  E  E  L  Z  Z   L   Z   L   L   L
4    Z  L  L  E  Z  L  Z  E  Z   E   Z   Z   E   L
..  .. .. .. .. .. .. .. .. ..  ..  ..  ..  ..  ..
557  E  L  L  L  Z  Z  E  E  L   Z   L   E   Z   E
558  L  E  L  Z  L  Z  E  E  L   Z   L   L   L   Z
559  Z  L  L  E  Z  L  L  L  E   L   Z   L   L   L
560  L  Z  L  Z  L  L  Z  L  E   L   Z   L   E   Z
561  L  L  L  E  L  L  L  E  L   E   Z   E   E   Z

[562 rows x 14 columns]

In [618]:
data_new.columns

Index(['R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'R8', 'R9', 'R10', 'R11',
       'R12', 'R13', 'R14'],
      dtype='object')

In [619]:
lst = ['R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'R8', 'R9', 'R10', 'R11',
       'R12', 'R13', 'R14']

In [620]:
data_cond = pd.get_dummies(data_new[lst], drop_first = True)

In [621]:
data_cond

,R1_L,R1_Z,R2_L,R2_Z,R3_L,R3_Z,R4_L,R4_Z,R5_L,R5_Z,...,R10_L,R10_Z,R11_L,R11_Z,R12_L,R12_Z,R13_L,R13_Z,R14_L,R14_Z
0,1,0,0,0,0,0,0,1,0,1,...,1,0,1,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,1,0,1,0,1,0,0,0,0
2,0,0,1,0,0,1,0,0,1,0,...,0,1,0,1,0,0,0,1,1,0
3,0,0,0,1,0,1,0,0,0,0,...,1,0,0,1,1,0,1,0,1,0
4,0,1,1,0,1,0,0,0,0,1,...,0,0,0,1,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
557,0,0,1,0,1,0,1,0,0,1,...,0,1,1,0,0,0,0,1,0,0
558,1,0,0,0,1,0,0,1,1,0,...,0,1,1,0,1,0,1,0,0,1
559,0,1,1,0,1,0,0,0,0,1,...,1,0,0,1,1,0,1,0,1,0
560,1,0,0,1,1,0,0,1,1,0,...,1,0,0,1,1,0,0,0,0,1
561,1,0,1,0,1,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,1

In [622]:
data_final = pd.concat([data_new, data_cond], axis = 1)

In [623]:
data_final.drop(['R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'R8', 'R9', 'R10', 'R11',
       'R12', 'R13', 'R14'], axis=1 , inplace=True)

In [624]:
data_final

,R1_L,R1_Z,R2_L,R2_Z,R3_L,R3_Z,R4_L,R4_Z,R5_L,R5_Z,...,R10_L,R10_Z,R11_L,R11_Z,R12_L,R12_Z,R13_L,R13_Z,R14_L,R14_Z
0,1,0,0,0,0,0,0,1,0,1,...,1,0,1,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,1,0,1,0,1,0,0,0,0
2,0,0,1,0,0,1,0,0,1,0,...,0,1,0,1,0,0,0,1,1,0
3,0,0,0,1,0,1,0,0,0,0,...,1,0,0,1,1,0,1,0,1,0
4,0,1,1,0,1,0,0,0,0,1,...,0,0,0,1,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
557,0,0,1,0,1,0,1,0,0,1,...,0,1,1,0,0,0,0,1,0,0
558,1,0,0,0,1,0,0,1,1,0,...,0,1,1,0,1,0,1,0,0,1
559,0,1,1,0,1,0,0,0,0,1,...,1,0,0,1,1,0,1,0,1,0
560,1,0,0,1,1,0,0,1,1,0,...,1,0,0,1,1,0,0,0,0,1
561,1,0,1,0,1,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,1

In [625]:
data_final.columns

Index(['R1_L', 'R1_Z', 'R2_L', 'R2_Z', 'R3_L', 'R3_Z', 'R4_L', 'R4_Z', 'R5_L',
       'R5_Z', 'R6_L', 'R6_Z', 'R7_L', 'R7_Z', 'R8_L', 'R8_Z', 'R9_L', 'R9_Z',
       'R10_L', 'R10_Z', 'R11_L', 'R11_Z', 'R12_L', 'R12_Z', 'R13_L', 'R13_Z',
       'R14_L', 'R14_Z'],
      dtype='object')

In [626]:
X = data_final[['R1_L', 'R1_Z', 'R2_L', 'R2_Z', 'R3_L', 'R3_Z', 'R4_L', 'R4_Z']]

# Row5

In [627]:
#y = data_final[['R5_L',
 #      'R5_Z', 'R6_L', 'R6_Z', 'R7_L', 'R7_Z', 'R8_L', 'R8_Z', 'R9_L', 'R9_Z',
  #     'R10_L', 'R10_Z', 'R11_L', 'R11_Z', 'R12_L', 'R12_Z', 'R13_L', 'R13_Z',
   #    'R14_L', 'R14_Z']]
y = data_final[['R5_L']]

In [628]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=2)

In [629]:
random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X_train,y_train)
Y_pred = random_forest.predict(X_test)
random_forest.score(X_test, y_test)
acc_random_forest1 = round(random_forest.score(X_test, y_test) * 100, 2)

sk_report = classification_report(
    digits=6,
    y_true=y_test, 
    y_pred=Y_pred)
print("Accuracy" , acc_random_forest1)
print(sk_report)

<ipython-input-629-c9d4847f5304>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random_forest.fit(X_train,y_train)

Accuracy 68.42
              precision    recall  f1-score   support

           0   0.763158  0.763158  0.763158        38
           1   0.526316  0.526316  0.526316        19

    accuracy                       0.684211        57
   macro avg   0.644737  0.644737  0.644737        57
weighted avg   0.684211  0.684211  0.684211        57

In [630]:
Y_pred

array([1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=uint8)

In [631]:
data_L = pd.DataFrame(Y_pred)

In [632]:
data_L.columns = ['Row5_L']

In [633]:
data_L["Row5_L"].replace({1: "L"}, inplace=True)

In [634]:
from sklearn.metrics import accuracy_score

In [635]:
X = data_final[['R1_L', 'R1_Z', 'R2_L', 'R2_Z', 'R3_L', 'R3_Z', 'R4_L', 'R4_Z']]

In [636]:
y_z = data_final[['R5_Z']]

In [641]:
X_train_, X_test_, y_train_, y_test_ = train_test_split(X, y_z, test_size=0.10, random_state=25)

In [642]:
random_forest = RandomForestClassifier(n_estimators=10)
random_forest.fit(X_train,y_train)
Y_pred_ = random_forest.predict(X_test_)
random_forest.score(X_test_, y_test_)
acc_random_forest1 = round(random_forest.score(X_test_, y_test_) * 100, 2)

sk_report = classification_report(
    digits=6,
    y_true=y_test, 
    y_pred=Y_pred)
print("Accuracy" , acc_random_forest1)
print(sk_report)

Accuracy 68.42
              precision    recall  f1-score   support

           0   0.763158  0.763158  0.763158        38
           1   0.526316  0.526316  0.526316        19

    accuracy                       0.684211        57
   macro avg   0.644737  0.644737  0.644737        57
weighted avg   0.684211  0.684211  0.684211        57

<ipython-input-642-3da4e602e0a6>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random_forest.fit(X_train,y_train)

In [459]:
accuracy_score(y_test_, Y_pred_)

0.6140350877192983

In [460]:
data_1 = pd.DataFrame(Y_pred_)

In [461]:
data_1.columns = ['Row5_Z']

In [462]:
data_1["Row5_Z"].replace({1: "Z"}, inplace=True)

In [463]:
#data_1["Row5_L"] = data_L.copy()

In [464]:
#data_1

# Row 6

In [559]:
y = data_final[['R6_L']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=2)
random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X_train,y_train)
Y_pred = random_forest.predict(X_test)
random_forest.score(X_test, y_test)
acc_random_forest1 = round(random_forest.score(X_test, y_test) * 100, 2)

sk_report = classification_report(
    digits=6,
    y_true=y_test, 
    y_pred=Y_pred)
Row6_L = pd.DataFrame(Y_pred)
Row6_L.columns = ['Row6_L']
Row6_L["Row6_L"].replace({1: "L"}, inplace=True)
X = data_final[['R1_L', 'R1_Z', 'R2_L', 'R2_Z', 'R3_L', 'R3_Z', 'R4_L', 'R4_Z']]
y_z = data_final[['R6_Z']]
X_train_, X_test_, y_train_, y_test_ = train_test_split(X, y_z, test_size=0.10, random_state=2)
random_forest = RandomForestClassifier(n_estimators=10)
random_forest.fit(X_train,y_train)
Y_pred_ = random_forest.predict(X_test_)
random_forest.score(X_test_, y_test_)
acc_random_forest1 = round(random_forest.score(X_test_, y_test_) * 100, 2)

sk_report = classification_report(
    digits=6,
    y_true=y_test, 
    y_pred=Y_pred)
print("Accuracy" , acc_random_forest1)
print(sk_report)
accuracy_score(y_test_, Y_pred_)
Row6_Z = pd.DataFrame(Y_pred_)
Row6_Z.columns = ['Row6_Z']
Row6_Z["Row6_Z"].replace({1: "Z"}, inplace=True)
#Row6_L["Row6_Z"] = Row6_Z.copy()

<ipython-input-559-23d49ade7ee4>:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random_forest.fit(X_train,y_train)

Accuracy 66.67
              precision    recall  f1-score   support

           0   0.466667  0.777778  0.583333        27
           1   0.500000  0.200000  0.285714        30

    accuracy                       0.473684        57
   macro avg   0.483333  0.488889  0.434524        57
weighted avg   0.484211  0.473684  0.426692        57

<ipython-input-559-23d49ade7ee4>:20: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random_forest.fit(X_train,y_train)

# Row 7

In [669]:
y = data_final[['R7_L']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=10)
random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X_train,y_train)
Y_pred = random_forest.predict(X_test)
random_forest.score(X_test, y_test)
acc_random_forest1 = round(random_forest.score(X_test, y_test) * 100, 2)

sk_report = classification_report(
    digits=6,
    y_true=y_test, 
    y_pred=Y_pred)
Row7_L = pd.DataFrame(Y_pred)
print("Accuracy" , acc_random_forest1)
print(sk_report)
Row7_L.columns = ['Row7_L']
Row7_L["Row7_L"].replace({1: "L"}, inplace=True)
X = data_final[['R1_L', 'R1_Z', 'R2_L', 'R2_Z', 'R3_L', 'R3_Z', 'R4_L', 'R4_Z']]
y_z = data_final[['R7_Z']]
X_train_, X_test_, y_train_, y_test_ = train_test_split(X, y_z, test_size=0.10, random_state=21)
random_forest = RandomForestClassifier(n_estimators=10)
random_forest.fit(X_train,y_train)
Y_pred_ = random_forest.predict(X_test_)
random_forest.score(X_test_, y_test_)
acc_random_forest1 = round(random_forest.score(X_test_, y_test_) * 100, 2)

sk_report = classification_report(
    digits=6,
    y_true=y_test, 
    y_pred=Y_pred)
#print("Accuracy" , acc_random_forest1)
#print(sk_report)
accuracy_score(y_test_, Y_pred_)
Row7_Z = pd.DataFrame(Y_pred_)
Row7_Z.columns = ['Row7_Z']
Row7_Z["Row7_Z"].replace({1: "Z"}, inplace=True)
#Row7_L["Row7_Z"] = Row7_Z.copy()

<ipython-input-669-77edf6c16bad>:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random_forest.fit(X_train,y_train)

Accuracy 61.4
              precision    recall  f1-score   support

           0   0.702703  0.702703  0.702703        37
           1   0.450000  0.450000  0.450000        20

    accuracy                       0.614035        57
   macro avg   0.576351  0.576351  0.576351        57
weighted avg   0.614035  0.614035  0.614035        57

<ipython-input-669-77edf6c16bad>:22: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random_forest.fit(X_train,y_train)

In [570]:
Row7_L

   Row7_L
0       0
1       L
2       L
3       0
4       L
5       L
6       0
7       0
8       0
9       0
10      0
11      0
12      0
13      L
14      0
15      0
16      0
17      0
18      0
19      0
20      0
21      0
22      0
23      L
24      0
25      0
26      L
27      0
28      L
29      0
30      0
31      0
32      0
33      L
34      0
35      L
36      0
37      0
38      0
39      0
40      0
41      L
42      0
43      0
44      L
45      0
46      0
47      0
48      0
49      0
50      0
51      L
52      L
53      0
54      L
55      0
56      L

# Row8

In [590]:
y = data_final[['R8_L']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=2)
random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X_train,y_train)
Y_pred = random_forest.predict(X_test)
random_forest.score(X_test, y_test)
acc_random_forest1 = round(random_forest.score(X_test, y_test) * 100, 2)

sk_report = classification_report(
    digits=6,
    y_true=y_test, 
    y_pred=Y_pred)
print("Accuracy" , acc_random_forest1)
print(sk_report)
Row8_L = pd.DataFrame(Y_pred)
Row8_L.columns = ['Row8_L']
Row8_L["Row8_L"].replace({1: "L"}, inplace=True)
X = data_final[['R1_L', 'R1_Z', 'R2_L', 'R2_Z', 'R3_L', 'R3_Z', 'R4_L', 'R4_Z']]
y_z = data_final[['R8_Z']]
X_train_, X_test_, y_train_, y_test_ = train_test_split(X, y_z, test_size=0.10, random_state=2)
random_forest = RandomForestClassifier(n_estimators=10)
random_forest.fit(X_train,y_train)
Y_pred_ = random_forest.predict(X_test_)
random_forest.score(X_test_, y_test_)
acc_random_forest1 = round(random_forest.score(X_test_, y_test_) * 100, 2)

sk_report = classification_report(
    digits=6,
    y_true=y_test, 
    y_pred=Y_pred)
accuracy_score(y_test_, Y_pred_)
Row8_Z = pd.DataFrame(Y_pred_)
Row8_Z.columns = ['Row8_Z']
Row8_Z["Row8_Z"].replace({1: "Z"}, inplace=True)
#Row8_L["Row8_Z"] = Row8_Z.copy()

<ipython-input-590-0d76dcaa3e28>:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random_forest.fit(X_train,y_train)

Accuracy 64.91
              precision    recall  f1-score   support

           0   0.697674  0.810811  0.750000        37
           1   0.500000  0.350000  0.411765        20

    accuracy                       0.649123        57
   macro avg   0.598837  0.580405  0.580882        57
weighted avg   0.628315  0.649123  0.631321        57

<ipython-input-590-0d76dcaa3e28>:22: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random_forest.fit(X_train,y_train)

In [469]:
Row8_L

   Row8_L
0       0
1       0
2       0
3       0
4       0
5       0
6       0
7       0
8       L
9       0
10      L
11      0
12      0
13      0
14      0
15      0
16      0
17      L
18      0
19      0
20      L
21      0
22      0
23      0
24      0
25      L
26      0
27      0
28      L
29      0
30      0
31      0
32      0
33      0
34      0
35      0
36      0
37      0
38      0
39      0
40      L
41      L
42      0
43      L
44      0
45      L
46      0
47      0
48      0
49      L
50      0
51      0
52      L
53      L
54      0
55      0
56      L

# Row 9

In [591]:
y = data_final[['R9_L']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=2)
random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X_train,y_train)
Y_pred = random_forest.predict(X_test)
random_forest.score(X_test, y_test)
acc_random_forest1 = round(random_forest.score(X_test, y_test) * 100, 2)

sk_report = classification_report(
    digits=6,
    y_true=y_test, 
    y_pred=Y_pred)
print("Accuracy" , acc_random_forest1)
print(sk_report)
Row9_L = pd.DataFrame(Y_pred)
Row9_L.columns = ['Row9_L']
Row9_L["Row9_L"].replace({1: "L"}, inplace=True)
X = data_final[['R1_L', 'R1_Z', 'R2_L', 'R2_Z', 'R3_L', 'R3_Z', 'R4_L', 'R4_Z']]
y_z = data_final[['R9_Z']]
X_train_, X_test_, y_train_, y_test_ = train_test_split(X, y_z, test_size=0.10, random_state=2)
random_forest = RandomForestClassifier(n_estimators=10)
random_forest.fit(X_train,y_train)
Y_pred_ = random_forest.predict(X_test_)
random_forest.score(X_test_, y_test_)
acc_random_forest1 = round(random_forest.score(X_test_, y_test_) * 100, 2)

sk_report = classification_report(
    digits=6,
    y_true=y_test, 
    y_pred=Y_pred)
accuracy_score(y_test_, Y_pred_)
Row9_Z = pd.DataFrame(Y_pred_)
Row9_Z.columns = ['Row9_Z']
Row9_Z["Row9_Z"].replace({1: "Z"}, inplace=True)
#Row9_L["Row9_Z"] = Row9_Z.copy()

<ipython-input-591-fb12a4390825>:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random_forest.fit(X_train,y_train)

Accuracy 66.67
              precision    recall  f1-score   support

           0   0.771429  0.710526  0.739726        38
           1   0.500000  0.578947  0.536585        19

    accuracy                       0.666667        57
   macro avg   0.635714  0.644737  0.638156        57
weighted avg   0.680952  0.666667  0.672012        57

<ipython-input-591-fb12a4390825>:22: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random_forest.fit(X_train,y_train)

In [539]:
Row9_L

   Row9_L
0       0
1       L
2       L
3       0
4       0
5       L
6       L
7       0
8       0
9       L
10      0
11      L
12      0
13      L
14      0
15      0
16      0
17      0
18      0
19      0
20      L
21      0
22      0
23      L
24      0
25      0
26      L
27      L
28      L
29      0
30      0
31      0
32      0
33      0
34      0
35      L
36      0
37      0
38      L
39      L
40      0
41      L
42      0
43      0
44      L
45      0
46      L
47      0
48      0
49      0
50      L
51      L
52      0
53      0
54      0
55      L
56      L

# Row 10

In [592]:
y = data_final[['R10_L']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=2)
random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X_train,y_train)
Y_pred = random_forest.predict(X_test)
random_forest.score(X_test, y_test)
acc_random_forest1 = round(random_forest.score(X_test, y_test) * 100, 2)

sk_report = classification_report(
    digits=6,
    y_true=y_test, 
    y_pred=Y_pred)
print("Accuracy" , acc_random_forest1)
print(sk_report)
Row10_L = pd.DataFrame(Y_pred)
Row10_L.columns = ['Row10_L']
Row10_L["Row10_L"].replace({1: "L"}, inplace=True)
X = data_final[['R1_L', 'R1_Z', 'R2_L', 'R2_Z', 'R3_L', 'R3_Z', 'R4_L', 'R4_Z']]
y_z = data_final[['R10_Z']]
X_train_, X_test_, y_train_, y_test_ = train_test_split(X, y_z, test_size=0.10, random_state=2)
random_forest = RandomForestClassifier(n_estimators=10)
random_forest.fit(X_train,y_train)
Y_pred_ = random_forest.predict(X_test_)
random_forest.score(X_test_, y_test_)
acc_random_forest1 = round(random_forest.score(X_test_, y_test_) * 100, 2)

sk_report = classification_report(
    digits=6,
    y_true=y_test, 
    y_pred=Y_pred)
accuracy_score(y_test_, Y_pred_)
Row10_Z = pd.DataFrame(Y_pred_)
Row10_Z.columns = ['Row10_Z']
Row10_Z["Row10_Z"].replace({1: "Z"}, inplace=True)
#Row10_L["Row10_Z"] = Row10_Z.copy()

<ipython-input-592-940eccc59f41>:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random_forest.fit(X_train,y_train)

Accuracy 63.16
              precision    recall  f1-score   support

           0   0.684211  0.742857  0.712329        35
           1   0.526316  0.454545  0.487805        22

    accuracy                       0.631579        57
   macro avg   0.605263  0.598701  0.600067        57
weighted avg   0.623269  0.631579  0.625670        57

<ipython-input-592-940eccc59f41>:22: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random_forest.fit(X_train,y_train)

In [473]:
Row10_L

   Row10_L
0        0
1        0
2        0
3        0
4        L
5        L
6        0
7        0
8        0
9        0
10       0
11       0
12       L
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       L
21       L
22       0
23       0
24       L
25       0
26       0
27       0
28       0
29       0
30       L
31       L
32       0
33       L
34       L
35       L
36       L
37       0
38       0
39       0
40       0
41       L
42       L
43       L
44       0
45       0
46       0
47       0
48       0
49       0
50       0
51       L
52       0
53       0
54       L
55       0
56       0

# Row 11

In [605]:
y = data_final[['R11_L']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=2)
random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X_train,y_train)
Y_pred = random_forest.predict(X_test)
random_forest.score(X_test, y_test)
acc_random_forest1 = round(random_forest.score(X_test, y_test) * 100, 2)

sk_report = classification_report(
    digits=6,
    y_true=y_test, 
    y_pred=Y_pred)
Row11_L = pd.DataFrame(Y_pred)
Row11_L.columns = ['Row11_L']
Row11_L["Row11_L"].replace({1: "L"}, inplace=True)
X = data_final[['R1_L', 'R1_Z', 'R2_L', 'R2_Z', 'R3_L', 'R3_Z', 'R4_L', 'R4_Z']]
y_z = data_final[['R11_Z']]
X_train_, X_test_, y_train_, y_test_ = train_test_split(X, y_z, test_size=0.10, random_state=26)
random_forest = RandomForestClassifier(n_estimators=10)
random_forest.fit(X_train,y_train)
Y_pred_ = random_forest.predict(X_test_)
random_forest.score(X_test_, y_test_)
acc_random_forest1 = round(random_forest.score(X_test_, y_test_) * 100, 2)

sk_report = classification_report(
    digits=6,
    y_true=y_test, 
    y_pred=Y_pred)
print("Accuracy" , acc_random_forest1)
print(sk_report)
accuracy_score(y_test_, Y_pred_)
Row11_Z = pd.DataFrame(Y_pred_)
Row11_Z.columns = ['Row11_Z']
Row11_Z["Row11_Z"].replace({1: "Z"}, inplace=True)
#Row11_L["Row11_Z"] = Row11_Z.copy()

<ipython-input-605-d27af7d6bd26>:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random_forest.fit(X_train,y_train)

Accuracy 61.4
              precision    recall  f1-score   support

           0   0.514286  0.545455  0.529412        33
           1   0.318182  0.291667  0.304348        24

    accuracy                       0.438596        57
   macro avg   0.416234  0.418561  0.416880        57
weighted avg   0.431716  0.438596  0.434648        57

<ipython-input-605-d27af7d6bd26>:20: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random_forest.fit(X_train,y_train)

# Row 12

In [612]:
y = data_final[['R12_L']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=2)
random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X_train,y_train)
Y_pred = random_forest.predict(X_test)
random_forest.score(X_test, y_test)
acc_random_forest1 = round(random_forest.score(X_test, y_test) * 100, 2)

sk_report = classification_report(
    digits=6,
    y_true=y_test, 
    y_pred=Y_pred)
Row12_L = pd.DataFrame(Y_pred)
Row12_L.columns = ['Row12_L']
Row12_L["Row12_L"].replace({1: "L"}, inplace=True)
X = data_final[['R1_L', 'R1_Z', 'R2_L', 'R2_Z', 'R3_L', 'R3_Z', 'R4_L', 'R4_Z']]
y_z = data_final[['R12_Z']]
X_train_, X_test_, y_train_, y_test_ = train_test_split(X, y_z, test_size=0.10, random_state=2)
random_forest = RandomForestClassifier(n_estimators=10)
random_forest.fit(X_train,y_train)
Y_pred_ = random_forest.predict(X_test_)
random_forest.score(X_test_, y_test_)
acc_random_forest1 = round(random_forest.score(X_test_, y_test_) * 100, 2)

sk_report = classification_report(
    digits=6,
    y_true=y_test, 
    y_pred=Y_pred)
print("Accuracy" , acc_random_forest1)
print(sk_report)
accuracy_score(y_test_, Y_pred_)
Row12_Z = pd.DataFrame(Y_pred_)
Row12_Z.columns = ['Row12_Z']
Row12_Z["Row12_Z"].replace({1: "Z"}, inplace=True)
#Row12_L["Row12_Z"] = Row12_Z.copy()

<ipython-input-612-6e87f334931e>:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random_forest.fit(X_train,y_train)

Accuracy 64.91
              precision    recall  f1-score   support

           0   0.558824  0.575758  0.567164        33
           1   0.391304  0.375000  0.382979        24

    accuracy                       0.491228        57
   macro avg   0.475064  0.475379  0.475071        57
weighted avg   0.488289  0.491228  0.489612        57

<ipython-input-612-6e87f334931e>:20: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random_forest.fit(X_train,y_train)

# Row 13

In [606]:
y = data_final[['R13_L']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=2)
random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X_train,y_train)
Y_pred = random_forest.predict(X_test)
random_forest.score(X_test, y_test)
acc_random_forest1 = round(random_forest.score(X_test, y_test) * 100, 2)

sk_report = classification_report(
    digits=6,
    y_true=y_test, 
    y_pred=Y_pred)
Row13_L = pd.DataFrame(Y_pred)
Row13_L.columns = ['Row13_L']
Row13_L["Row13_L"].replace({1: "L"}, inplace=True)
X = data_final[['R1_L', 'R1_Z', 'R2_L', 'R2_Z', 'R3_L', 'R3_Z', 'R4_L', 'R4_Z']]
y_z = data_final[['R13_Z']]
X_train_, X_test_, y_train_, y_test_ = train_test_split(X, y_z, test_size=0.10, random_state=2)
random_forest = RandomForestClassifier(n_estimators=10)
random_forest.fit(X_train,y_train)
Y_pred_ = random_forest.predict(X_test_)
random_forest.score(X_test_, y_test_)
acc_random_forest1 = round(random_forest.score(X_test_, y_test_) * 100, 2)

sk_report = classification_report(
    digits=6,
    y_true=y_test, 
    y_pred=Y_pred)
print("Accuracy" , acc_random_forest1)
print(sk_report)
accuracy_score(y_test_, Y_pred_)
Row13_Z = pd.DataFrame(Y_pred_)
Row13_Z.columns = ['Row13_Z']
Row13_Z["Row13_Z"].replace({1: "Z"}, inplace=True)
#Row13_L["Row13_Z"] = Row13_Z.copy()

<ipython-input-606-d613f776b930>:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random_forest.fit(X_train,y_train)

Accuracy 77.19
              precision    recall  f1-score   support

           0   0.658537  0.675000  0.666667        40
           1   0.187500  0.176471  0.181818        17

    accuracy                       0.526316        57
   macro avg   0.423018  0.425735  0.424242        57
weighted avg   0.518052  0.526316  0.522063        57

<ipython-input-606-d613f776b930>:20: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random_forest.fit(X_train,y_train)

# Row 14

In [607]:
y = data_final[['R14_L']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.10, random_state=2)
random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X_train,y_train)
Y_pred = random_forest.predict(X_test)
random_forest.score(X_test, y_test)
acc_random_forest1 = round(random_forest.score(X_test, y_test) * 100, 2)

sk_report = classification_report(
    digits=6,
    y_true=y_test, 
    y_pred=Y_pred)
Row14_L = pd.DataFrame(Y_pred)
Row14_L.columns = ['Row14_L']
Row14_L["Row14_L"].replace({1: "L"}, inplace=True)
X = data_final[['R1_L', 'R1_Z', 'R2_L', 'R2_Z', 'R3_L', 'R3_Z', 'R4_L', 'R4_Z']]
y_z = data_final[['R14_Z']]
X_train_, X_test_, y_train_, y_test_ = train_test_split(X, y_z, test_size=0.10, random_state=2)
random_forest = RandomForestClassifier(n_estimators=10)
random_forest.fit(X_train,y_train)
Y_pred_ = random_forest.predict(X_test_)
random_forest.score(X_test_, y_test_)
acc_random_forest1 = round(random_forest.score(X_test_, y_test_) * 100, 2)

sk_report = classification_report(
    digits=6,
    y_true=y_test, 
    y_pred=Y_pred)
print("Accuracy" , acc_random_forest1)
print(sk_report)
accuracy_score(y_test_, Y_pred_)
Row14_Z = pd.DataFrame(Y_pred_)
Row14_Z.columns = ['Row14_Z']
Row14_Z["Row14_Z"].replace({1: "Z"}, inplace=True)
#Row14_L["Row14_Z"] = Row14_Z.copy()

<ipython-input-607-8df030f45d73>:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random_forest.fit(X_train,y_train)

Accuracy 63.16
              precision    recall  f1-score   support

           0   0.473684  0.600000  0.529412        30
           1   0.368421  0.259259  0.304348        27

    accuracy                       0.438596        57
   macro avg   0.421053  0.429630  0.416880        57
weighted avg   0.423823  0.438596  0.422803        57

<ipython-input-607-8df030f45d73>:20: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random_forest.fit(X_train,y_train)

In [478]:
Row14_L

   Row14_L
0        L
1        0
2        0
3        L
4        0
5        0
6        0
7        0
8        0
9        0
10       L
11       0
12       L
13       L
14       0
15       0
16       L
17       0
18       L
19       0
20       0
21       L
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       L
30       0
31       0
32       0
33       0
34       0
35       L
36       0
37       0
38       L
39       0
40       0
41       0
42       0
43       L
44       0
45       L
46       0
47       L
48       0
49       L
50       0
51       0
52       L
53       L
54       L
55       0
56       0

In [670]:
new = data_L.copy()

In [671]:
new["Row5_Z"] = data_1.copy()

In [672]:
new["Row6_L"] = Row6_L.copy()

In [673]:
new["Row6_Z"] = Row6_Z.copy()

In [674]:
new["Row7_L"] = Row7_L.copy()

In [675]:
new["Row7_Z"] = Row7_Z.copy()

In [676]:
new["Row8_L"] = Row8_L.copy()

In [677]:
new["Row8_Z"] = Row8_Z.copy()

In [678]:
new["Row9_L"] = Row9_L.copy()

In [679]:
new["Row9_Z"] = Row9_Z.copy()

In [680]:
new["Row10_L"] = Row10_L.copy()

In [681]:
new["Row10_Z"] = Row10_Z.copy()

In [682]:
new["Row11_L"] = Row11_L.copy()

In [683]:
new["Row11_Z"] = Row11_Z.copy()

In [684]:
new["Row12_L"] = Row12_L.copy()

In [685]:
new["Row12_Z"] = Row12_Z.copy()

In [686]:
new["Row13_L"] = Row13_L.copy()

In [687]:
new["Row13_Z"] = Row13_Z.copy()

In [688]:
new["Row14_L"] = Row14_L.copy()

In [689]:
new["Row14_Z"] = Row14_Z.copy()

In [690]:
new

,Row5_L,Row5_Z,Row6_L,Row6_Z,Row7_L,Row7_Z,Row8_L,Row8_Z,Row9_L,Row9_Z,Row10_L,Row10_Z,Row11_L,Row11_Z,Row12_L,Row12_Z,Row13_L,Row13_Z,Row14_L,Row14_Z
0,L,Z,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,L,Z
1,L,Z,L,Z,L,0,0,0,L,Z,0,0,L,0,L,Z,0,0,0,0
2,L,Z,L,Z,0,0,0,0,L,Z,0,0,L,0,L,Z,0,0,0,0
3,0,0,0,0,L,0,0,0,0,0,L,0,0,0,L,Z,0,0,L,Z
4,0,0,0,0,0,0,0,0,0,0,L,Z,L,0,0,0,0,0,0,0
5,L,0,0,0,0,Z,0,0,L,Z,L,Z,0,0,L,Z,0,0,0,0
6,0,0,0,0,L,Z,0,Z,L,Z,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,L,Z,0,0,0,0,0,0,0,Z,0,0,0,0,0,0
8,0,Z,L,0,L,0,L,Z,0,0,0,0,0,0,0,Z,L,Z,L,Z
9,0,0,L,0,0,0,0,0,L,0,L,0,0,Z,L,0,L,0,0,0
10,0,0,0,0,0,0,L,Z,0,0,0,0,L,0,L,Z,0,0,L,Z
11,0,Z,0,0,L,0,0,0,L,Z,0,0,0,0,0,0,L,Z,0,0
12,0,Z,0,0,0,Z,0,0,0,0,0,Z,L,0,0,0,0,0,L,0
13,L,0,0,0,L,0,0,0,L,Z,0,0,L,0,L,0,0,0,L,Z
14,0,0,0,0,L,Z,0,0,0,0,0,0,L,0,L,0,L,Z,0,0
15,0,0,0,0,L,0,0,Z,0,0,0,0,L,0,L,Z,L,Z,0,0
16,0,Z,0,Z,L,0,0,0,0,0,0,0,L,0,0,0,L,0,L,Z
17,L,0,0,0,0,0,L,0,0,0,0,0,L,Z,L,Z,L,0,0,0
18,L,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,L,Z
19,0,0,0,0,L,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
20,0,Z,0,0,L,Z,L,Z,L,Z,L,Z,0,0,0,Z,0,0,0,0
21,L,0,0,0,0,0,0,0,0,0,L,Z,0,Z,0,0,0,0,L,0
22,L,0,0,Z,L,0,0,0,0,Z,0,0,0,Z,0,0,0,0,0,0
23,L,0,L,Z,L,0,0,0,L,Z,0,0,L,0,L,Z,0,0,0,0
24,0,0,L,Z,0,0,0,0,0,0,L,Z,0,0,0,0,0,0,0,0
25,L,Z,L,Z,0,0,L,Z,0,0,0,0,L,0,L,Z,0,0,0,Z
26,0,0,0,Z,0,0,0,Z,0,Z,0,0,0,0,0,Z,0,0,0,0
27,0,0,0,0,0,0,0,Z,L,Z,0,0,0,0,0,0,0,0,0,0
28,0,Z,0,0,0,Z,L,Z,L,Z,0,0,L,Z,0,0,L,Z,0,0
29,L,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,L,Z
30,0,0,0,0,0,Z,0,0,0,0,L,Z,0,0,0,Z,L,Z,0,0
31,L,0,0,0,0,Z,0,0,0,0,L,Z,0,0,0,0,L,Z,0,0
32,0,0,0,0,L,0,0,Z,0,0,0,0,L,Z,L,Z,L,Z,0,0
33,0,0,L,Z,L,0,0,0,0,Z,L,Z,0,Z,L,Z,0,0,0,0
34,0,0,0,0,0,0,0,0,0,0,L,Z,0,0,L,Z,0,0,0,0
35,L,0,L,Z,0,0,0,0,L,Z,L,Z,L,0,0,Z,L,Z,L,Z
36,0,0,0,0,0,0,0,0,0,0,L,Z,0,Z,L,Z,0,0,0,0
37,L,Z,0,Z,0,Z,0,0,0,0,0,0,0,Z,0,0,0,0,0,0
38,0,0,0,0,0,Z,0,0,L,Z,0,0,0,Z,0,0,0,0,L,Z
39,0,Z,0,0,0,0,0,0,L,Z,0,0,0,0,0,0,0,0,0,0
40,0,0,0,0,0,0,L,Z,0,0,0,0,0,Z,L,Z,0,0,0,0
41,0,Z,L,Z,0,0,L,Z,L,Z,L,Z,L,0,L,Z,0,0,0,0
42,0,Z,L,Z,0,0,0,0,0,0,L,Z,0,0,0,0,0,0,0,0
43,L,0,0,0,0,Z,0,Z,0,0,L,Z,L,Z,0,0,0,0,L,Z
44,L,Z,L,Z,0,0,0,0,L,Z,0,0,L,0,L,Z,0,0,0,0
45,0,0,0,0,L,0,L,Z,0,0,0,0,L,0,L,Z,0,0,L,Z
46,0,0,0,0,L,0,0,Z,L,Z,0,0,0,0,0,0,0,0,0,0
47,L,Z,0,0,L,0,0,Z,0,0,L,0,0,0,L,Z,0,Z,L,Z
48,0,0,0,0,0,Z,0,0,0,0,0,0,0,0,0,0,0,0,0,0
49,0,0,0,0,0,0,L,Z,0,0,0,0,0,0,0,0,0,0,L,Z
50,0,0,0,0,0,0,L,Z,L,Z,0,0,0,Z,0,0,0,Z,0,0
51,L,Z,0,0,L,0,0,0,L,Z,L,Z,L,0,L,Z,L,Z,0,Z
52,0,0,0,0,0,Z,L,Z,L,0,0,0,0,Z,0,Z,L,0,L,Z
53,0,Z,0,0,0,0,L,Z,0,0,0,0,0,0,0,0,0,0,L,Z
54,0,0,0,0,0,0,0,0,0,0,L,Z,L,0,L,Z,L,Z,L,Z
55,0,0,0,0,0,0,0,Z,L,Z,0,0,0,Z,0,0,0,0,0,0
56,0,0,0,0,0,0,L,Z,L,Z,0,0,L,0,0,0,L,Z,0,0